language: python
python:
  - "3.6"

cache:
  directories:
    - $HOME/.pip-cache/

# ignore the virtualenv that Travis creates
# setup a secure login to CodeCov
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - secure: ef24184f-79a4-4e63-8645-fd9e7553d715
git:
  submodules:
    false

before_install:
  - gem install mdl
  - echo -e "machine github.com\n  login pytest-blame-travis\n  password Allegheny2019" > ~/.netrc
  - git submodule update --init --recursive

notifications:
  email: never

# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install --upgrade pipenv
  - pipenv install --dev
script:
  - shopt -s globstar
  - pipenv run pytest tests --cov-config pytest.cov --cov
  - pipenv run black **/*.py --check
  - pipenv run flake8 **/*.py
  - pipenv run pylint **/*.py
  - mdl README.rst

# report coverage information to CodeCov
after_success:
  - pipenv run codecov
